import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";



export const metadata: Metadata = {
	title: "Teatar 011",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="sr-Rs">
			<body className="bg-neutral-900 text-slate-50">
				<header className="bg-neutral-950">
					<Navbar></Navbar>
				</header>
				
				<main>
					{children}
				</main>
				<footer></footer>
			</body>
		</html>
	);
}
